const NUDJ = 'NUDJ'
const INTERNAL_EMAIL_ADDRESS = 'hello@nudj.co'
const INTERNAL_EMAIL_FROM = `nudj <${INTERNAL_EMAIL_ADDRESS}>`

module.exports = {
  NUDJ,
  INTERNAL_EMAIL_ADDRESS,
  INTERNAL_EMAIL_FROM
}
