const NUDJ = 'NUDJ'
const INTERNAL_EMAIL_ADDRESS = 'hello@nudj.co'
const INTERNAL_EMAIL_FROM = `nudj <${INTERNAL_EMAIL_ADDRESS}>`
const DUMMY_APPLICANT_EMAIL_ADDRESS = 'hello+applicant@nudj.co'

module.exports = {
  NUDJ,
  INTERNAL_EMAIL_ADDRESS,
  INTERNAL_EMAIL_FROM,
  DUMMY_APPLICANT_EMAIL_ADDRESS
}
