const {
  TABLES,
  FIELDS
} = require('../../lib/sql')

const TABLE_ORDER = [
  TABLES.PEOPLE,
  TABLES.COMPANIES,
  TABLES.JOBS,
  TABLES.HIRERS,
  TABLES.REFERRALS,
  TABLES.APPLICATIONS,
  TABLES.EMPLOYMENTS,
  TABLES.EMPLOYEES,
  TABLES.ROLES,
  TABLES.PERSON_ROLES,
  TABLES.CONNECTIONS,
  TABLES.ACCOUNTS,
  TABLES.CONVERSATIONS,
  TABLES.VIEW_EVENTS,
  TABLES.SURVEYS,
  TABLES.SURVEY_SECTIONS,
  TABLES.SURVEY_QUESTIONS,
  TABLES.SURVEY_ANSWERS,
  TABLES.SURVEY_ANSWER_CONNECTIONS,
  TABLES.TAGS,
  TABLES.JOB_TAGS,
  TABLES.ROLE_TAGS,
  TABLES.SURVEY_QUESTION_TAGS
]
const TABLE_TO_COLLECTION = {
  [TABLES.VIEW_EVENTS]: 'events'
}
const RELATIONS = {
  [TABLES.JOBS]: {
    [FIELDS[TABLES.JOBS].COMPANY]: TABLES.COMPANIES
  },
  [TABLES.HIRERS]: {
    [FIELDS[TABLES.HIRERS].PERSON]: TABLES.PEOPLE,
    [FIELDS[TABLES.HIRERS].COMPANY]: TABLES.COMPANIES
  },
  [TABLES.REFERRALS]: {
    [FIELDS[TABLES.REFERRALS].PERSON]: TABLES.PEOPLE,
    [FIELDS[TABLES.REFERRALS].JOB]: TABLES.JOBS,
    [FIELDS[TABLES.REFERRALS].PARENT]: TABLES.REFERRALS
  },
  [TABLES.APPLICATIONS]: {
    [FIELDS[TABLES.APPLICATIONS].PERSON]: TABLES.PEOPLE,
    [FIELDS[TABLES.APPLICATIONS].JOB]: TABLES.JOBS,
    [FIELDS[TABLES.APPLICATIONS].REFERRAL]: TABLES.REFERRALS
  },
  [TABLES.EMPLOYMENTS]: {
    [FIELDS[TABLES.EMPLOYMENTS].PERSON]: TABLES.PEOPLE,
    [FIELDS[TABLES.EMPLOYMENTS].COMPANY]: TABLES.COMPANIES
  },
  [TABLES.EMPLOYEES]: {
    [FIELDS[TABLES.EMPLOYEES].PERSON]: TABLES.PEOPLE,
    [FIELDS[TABLES.EMPLOYEES].COMPANY]: TABLES.COMPANIES
  },
  [TABLES.PERSON_ROLES]: {
    [FIELDS[TABLES.PERSON_ROLES].PERSON]: TABLES.PEOPLE,
    [FIELDS[TABLES.PERSON_ROLES].ROLE]: TABLES.ROLES
  },
  [TABLES.CONNECTIONS]: {
    [FIELDS[TABLES.CONNECTIONS].PERSON]: TABLES.PEOPLE,
    [FIELDS[TABLES.CONNECTIONS].FROM]: TABLES.PEOPLE,
    [FIELDS[TABLES.CONNECTIONS].ROLE]: TABLES.ROLES,
    [FIELDS[TABLES.CONNECTIONS].COMPANY]: TABLES.COMPANIES
  }
}
const SELF_RELATIONS = {
  [TABLES.REFERRALS]: [FIELDS[TABLES.REFERRALS].PARENT]
}
const tableToCollection = table => TABLE_TO_COLLECTION[table] || table
const dateToTimestamp = date => date.replace('T', ' ').replace('Z', '')

module.exports = {
  TABLE_ORDER,
  RELATIONS,
  SELF_RELATIONS,
  tableToCollection,
  dateToTimestamp
}
