const {
  TABLES,
  FIELDS
} = require('../../lib/sql')

const TABLE_ORDER = [
  TABLES.PEOPLE,
  TABLES.COMPANIES,
  TABLES.JOBS,
  TABLES.HIRERS,
  TABLES.REFERRALS,
  TABLES.APPLICATIONS,
  TABLES.EMPLOYMENTS,
  TABLES.EMPLOYEES,
  TABLES.ROLES,
  TABLES.PERSON_ROLES,
  TABLES.CONNECTIONS,
  TABLES.ACCOUNTS,
  TABLES.CONVERSATIONS,
  TABLES.VIEW_EVENTS,
  TABLES.SURVEYS,
  TABLES.SURVEY_SECTIONS,
  TABLES.SURVEY_QUESTIONS,
  TABLES.SURVEY_ANSWERS,
  TABLES.SURVEY_ANSWER_CONNECTIONS,
  TABLES.TAGS,
  TABLES.JOB_TAGS,
  TABLES.ROLE_TAGS,
  TABLES.SURVEY_QUESTION_TAGS
]
const TABLE_TO_COLLECTION = {
  [TABLES.VIEW_EVENTS]: 'events'
}
const RELATIONS = {
  [TABLES.JOBS]: {
    [FIELDS[TABLES.JOBS].COMPANY]: TABLES.COMPANIES
  }
}
const tableToCollection = table => TABLE_TO_COLLECTION[table] || table
const dateToTimestamp = date => date.replace('T', ' ').replace('Z', '')

module.exports = {
  TABLE_ORDER,
  RELATIONS,
  tableToCollection,
  dateToTimestamp
}
