version: '2'
services:
  api:
    image: nudj/api:development
    environment:
      - NPM_TOKEN
    env_file: ../api/.env
    volumes:
      - ../api/.zshrc:/root/.zshrc
      - ../api/src/gql:/usr/src/gql
      - ../api/src/lib:/usr/src/lib
      - ../api/src/rest:/usr/src/rest
      - ../api/src/test:/usr/src/test
      - ../api/src/.npmignore:/usr/src/.npmignore
      - ../api/src/.npmrc:/usr/src/.npmrc
      - ../api/src/nodemon.json:/usr/src/nodemon.json
      - ../api/src/package.json:/usr/src/package.json
      - ../api/src/index.js:/usr/src/index.js
    stdin_open: true
    command: /bin/zsh
